from pydantic import BaseModel
from typing import Optional

class User(BaseModel):
    id: Optional[int]  # Optional as it will be generated by the database
    username: str
    password: str
    is_online: Optional[bool] = False
    email: Optional[str] = None
    disable: Optional[bool] = False
    pic: Optional[str] = None
    creation_date: Optional[str] = None  # You can change the type to datetime if needed
    lpid: int

class TokenData(BaseModel):
    username: str | None = None

class UserInDB(User):
    hashed_password: str